name = "twine-spool-service"
main = "build/worker/shim.mjs"
compatibility_date = "2024-05-31"
account_id = "e13789758f8ce4b13f01d121f8a1d028"

[build]
command = "cargo install -q worker-build && worker-build --release"

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "spool-prod"
database_id = "9f6220b6-25f3-4bc0-979a-c5803785ef3b"

[assets]
directory = "./assets/"
binding = "ASSETS"
run_worker_first = true

[triggers]
crons = ["*/5 * * * *"]

[[env.dev.d1_databases]]
binding = "DB"
database_name = "spool-dev"
database_id = "31c8b3c3-e3b8-4037-86fd-ea73357971a6"

[env.dev.vars]
ACCEPT_ALL_STRANDS = "true"
MAX_BATCH_SIZE = "10000"

